-- ----------------------------
-- Table structure for REQUEST_LOG
-- ----------------------------
CREATE TABLE "MYTELPAY_ADAPTER"."REQUEST_LOG"
(
    "ID"                    NUMBER(19, 0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL ENABLE,
    "CLIENT_ID"             VARCHAR2(36 CHAR),
    "DESTINATION"           VARCHAR2(100 CHAR),
    "DURATION"              NUMBER(19, 0),
    "ERROR_CODE"            VARCHAR2(50 CHAR),
    "ERROR_DESCRIPTION"     CLOB,
    "ERROR_DETAIL"          CLOB,
    "HTTP_CODE"             NUMBER(10, 0),
    "METHOD"                VARCHAR2(10 CHAR),
    "PARTNER_CODE"          VARCHAR2(50 CHAR),
    "PARTNER_REQUEST_DATA"  CLOB,
    "PARTNER_RESPONSE_DATA" CLOB,
    "PARTNER_URI"           CLOB,
    "REQUEST_DATA"          CLOB,
    "REQUEST_TIME"          TIMESTAMP(6),
    "REQUEST_URI"           VARCHAR2(2000 CHAR),
    "RESPONSE_DATA"         CLOB,
    "RESPONSE_TIME"         TIMESTAMP(6),
    "SERVICE_CODE"          VARCHAR2(50 CHAR),
    "SOURCE"                VARCHAR2(100 CHAR),
    "REF_TRANS_ID"          VARCHAR2(100 CHAR)
);
-- ----------------------------
-- Primary Key structure for table REQUEST_LOG
-- ----------------------------
ALTER TABLE "MYTELPAY_ADAPTER"."REQUEST_LOG"
    ADD CONSTRAINT "PK_REQUEST_LOG" PRIMARY KEY ("ID")
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE (INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
            BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
-- ----------------------------
-- Table structure for CLIENT
-- ----------------------------
CREATE TABLE "MYTELPAY_ADAPTER"."CLIENT"
(
    "CLIENT_ID"        VARCHAR2(36 CHAR) NOT NULL ENABLE,
    "CLIENT_SECRET"    VARCHAR2(255 CHAR),
    "NAME"             VARCHAR2(100 CHAR),
    "SCOPE"            VARCHAR2(1000 CHAR),
    "CREATED_AT"       TIMESTAMP(6),
    "LAST_MODIFIED_AT" TIMESTAMP(6),
    "LAST_MODIFIED_BY" VARCHAR2(50 CHAR),
    "CREATED_BY"       VARCHAR2(50)
);
-- ----------------------------
-- Primary Key structure for table CLIENT
-- ----------------------------
ALTER TABLE "MYTELPAY_ADAPTER"."CLIENT"
    ADD CONSTRAINT "PK_CLIENT" PRIMARY KEY ("CLIENT_ID")
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE (INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
            BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);


CREATE TABLE "MYTELPAY_ADAPTER"."PRODUCT_INQUIRY_LOG"
   (	"ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"CREATED_TIME" TIMESTAMP (6),
	"PRODUCT_DATA" CLOB,
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
 LOB ("PRODUCT_DATA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))

